# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Upload to Closed Test Internal Track"
    lane :upload_to_closed_test_internal do
    gradle(task: 'clean')
    previous_build_number = google_play_track_version_codes(track: "internal")[0]
    new_build_number = previous_build_number + 1
    increment_version_code(gradle_file_path: "app/build.gradle.kts", version_code: new_build_number)
    gradle(
      task: 'bundle',
      build_type: 'release',
      print_command: false,
      properties: {
    	"android.injected.signing.store.file" => "/home/circleci/project/release.keystore",
   	"android.injected.signing.store.password" => ENV["RELEASE_STORE_PASSWORD"],
    	"android.injected.signing.key.alias" => ENV["RELEASE_KEY_ALIAS"],
    	"android.injected.signing.key.password" => ENV["RELEASE_KEY_PASSWORD"],
  }
    )
    upload_to_play_store(
       track: "internal",
       #release_status: 'draft',
       skip_upload_apk: true,
       aab:"app/build/outputs/bundle/release/app-release.aab")
    end
end
